// <auto-generated />
using System;
using GalactiLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalactiLog.Data.Migrations
{
    [DbContext(typeof(GalactiLogContext))]
    [Migration("20260921173551_CustomColumns")]
    partial class CustomColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GalactiLog.Data.Entities.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ParentId");

                    b.HasIndex("TargetId");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("activity_events");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.CatalogCacheEntry", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<bool>("Negative")
                        .HasColumnType("INTEGER")
                        .HasColumnName("negative");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.HasKey("Source", "Key");

                    b.ToTable("catalog_cache");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.CustomColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("applies_to");

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("column_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<string>("DropdownOptions")
                        .HasColumnType("TEXT")
                        .HasColumnName("dropdown_options");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_custom_columns_display_order");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_custom_columns_slug");

                    b.ToTable("custom_columns");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.CustomColumnValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("TEXT")
                        .HasColumnName("column_id");

                    b.Property<Guid?>("MosaicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mosaic_id");

                    b.Property<string>("RigLabel")
                        .HasColumnType("TEXT")
                        .HasColumnName("rig_label");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId")
                        .HasDatabaseName("ix_custom_column_values_column");

                    b.HasIndex("MosaicId")
                        .HasDatabaseName("ix_custom_column_values_mosaic");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_custom_column_values_target");

                    b.ToTable("custom_column_values");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("AduMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adu_max");

                    b.Property<double?>("AduMean")
                        .HasColumnType("REAL")
                        .HasColumnName("adu_mean");

                    b.Property<double?>("AduMedian")
                        .HasColumnType("REAL")
                        .HasColumnName("adu_median");

                    b.Property<int?>("AduMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adu_min");

                    b.Property<double?>("AduStdev")
                        .HasColumnType("REAL")
                        .HasColumnName("adu_stdev");

                    b.Property<double?>("Airmass")
                        .HasColumnType("REAL")
                        .HasColumnName("airmass");

                    b.Property<double?>("AltitudeDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("altitude_deg");

                    b.Property<double?>("AmbientTemp")
                        .HasColumnType("REAL")
                        .HasColumnName("ambient_temp");

                    b.Property<double?>("ArcsecPerPixel")
                        .HasColumnType("REAL")
                        .HasColumnName("arcsec_per_pixel");

                    b.Property<string>("Camera")
                        .HasColumnType("TEXT")
                        .HasColumnName("camera");

                    b.Property<int?>("CameraGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("camera_gain");

                    b.Property<DateTime?>("CaptureDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("capture_date");

                    b.Property<double?>("CloudCover")
                        .HasColumnType("REAL")
                        .HasColumnName("cloud_cover");

                    b.Property<int?>("DetectedStars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("detected_stars");

                    b.Property<double?>("DewPoint")
                        .HasColumnType("REAL")
                        .HasColumnName("dew_point");

                    b.Property<double?>("Eccentricity")
                        .HasColumnType("REAL")
                        .HasColumnName("eccentricity");

                    b.Property<string>("EccentricitySource")
                        .HasColumnType("TEXT")
                        .HasColumnName("eccentricity_source");

                    b.Property<double?>("ExposureTime")
                        .HasColumnType("REAL")
                        .HasColumnName("exposure_time");

                    b.Property<double?>("FileMtime")
                        .HasColumnType("REAL")
                        .HasColumnName("file_mtime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path")
                        .UseCollation("NOCASE");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("FilterUsed")
                        .HasColumnType("TEXT")
                        .HasColumnName("filter_used");

                    b.Property<int?>("FocuserPosition")
                        .HasColumnType("INTEGER")
                        .HasColumnName("focuser_position");

                    b.Property<double?>("FocuserTemp")
                        .HasColumnType("REAL")
                        .HasColumnName("focuser_temp");

                    b.Property<double?>("Fwhm")
                        .HasColumnType("REAL")
                        .HasColumnName("fwhm");

                    b.Property<double?>("GuidingRmsArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("guiding_rms_arcsec");

                    b.Property<double?>("GuidingRmsDecArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("guiding_rms_dec_arcsec");

                    b.Property<double?>("GuidingRmsRaArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("guiding_rms_ra_arcsec");

                    b.Property<string>("GuidingRmsSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("guiding_rms_source");

                    b.Property<double?>("HfrStdev")
                        .HasColumnType("REAL")
                        .HasColumnName("hfr_stdev");

                    b.Property<double?>("Humidity")
                        .HasColumnType("REAL")
                        .HasColumnName("humidity");

                    b.Property<string>("ImageType")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_type");

                    b.Property<double?>("MedianFwhm")
                        .HasColumnType("REAL")
                        .HasColumnName("median_fwhm");

                    b.Property<double?>("MedianHfr")
                        .HasColumnType("REAL")
                        .HasColumnName("median_hfr");

                    b.Property<string>("PierSide")
                        .HasColumnType("TEXT")
                        .HasColumnName("pier_side");

                    b.Property<double?>("Pressure")
                        .HasColumnType("REAL")
                        .HasColumnName("pressure");

                    b.Property<string>("Provenance")
                        .HasColumnType("TEXT")
                        .HasColumnName("provenance");

                    b.Property<string>("RawHeaders")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_headers");

                    b.Property<Guid?>("ResolvedTargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_target_id");

                    b.Property<double?>("RotatorPosition")
                        .HasColumnType("REAL")
                        .HasColumnName("rotator_position");

                    b.Property<double?>("SensorTemp")
                        .HasColumnType("REAL")
                        .HasColumnName("sensor_temp");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<double?>("SkyQuality")
                        .HasColumnType("REAL")
                        .HasColumnName("sky_quality");

                    b.Property<string>("Telescope")
                        .HasColumnType("TEXT")
                        .HasColumnName("telescope");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_path");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_direction");

                    b.Property<double?>("WindGust")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_gust");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_speed");

                    b.HasKey("Id");

                    b.HasIndex("Airmass");

                    b.HasIndex("AmbientTemp");

                    b.HasIndex("Camera");

                    b.HasIndex("CaptureDate");

                    b.HasIndex("DetectedStars");

                    b.HasIndex("Eccentricity");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("FilterUsed");

                    b.HasIndex("FocuserTemp");

                    b.HasIndex("Fwhm");

                    b.HasIndex("GuidingRmsArcsec");

                    b.HasIndex("Humidity");

                    b.HasIndex("ImageType");

                    b.HasIndex("MedianHfr");

                    b.HasIndex("ResolvedTargetId");

                    b.HasIndex("SessionDate");

                    b.HasIndex("Telescope");

                    b.HasIndex("ImageType", "SessionDate");

                    b.ToTable("images");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.MergeCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("ReasonText")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason_text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("REAL")
                        .HasColumnName("similarity_score");

                    b.Property<int>("SourceImageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_image_count");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid?>("SuggestedTargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_target_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestedTargetId");

                    b.ToTable("merge_candidates");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.MergeManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LoserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("loser_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("LoserId");

                    b.HasIndex("WinnerId");

                    b.ToTable("merge_manifests");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.OpenNgcCatalogEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double?>("BMag")
                        .HasColumnType("REAL")
                        .HasColumnName("b_mag");

                    b.Property<string>("CommonNames")
                        .HasColumnType("TEXT")
                        .HasColumnName("common_names");

                    b.Property<string>("Constellation")
                        .HasColumnType("TEXT")
                        .HasColumnName("constellation");

                    b.Property<double?>("Dec")
                        .HasColumnType("REAL")
                        .HasColumnName("dec");

                    b.Property<double?>("MajorAxis")
                        .HasColumnType("REAL")
                        .HasColumnName("major_axis");

                    b.Property<string>("Messier")
                        .HasColumnType("TEXT")
                        .HasColumnName("messier");

                    b.Property<double?>("MinorAxis")
                        .HasColumnType("REAL")
                        .HasColumnName("minor_axis");

                    b.Property<double?>("PositionAngle")
                        .HasColumnType("REAL")
                        .HasColumnName("position_angle");

                    b.Property<double?>("Ra")
                        .HasColumnType("REAL")
                        .HasColumnName("ra");

                    b.Property<double?>("SurfaceBrightness")
                        .HasColumnType("REAL")
                        .HasColumnName("surface_brightness");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<double?>("VMag")
                        .HasColumnType("REAL")
                        .HasColumnName("v_mag");

                    b.HasKey("Name");

                    b.HasIndex("Messier");

                    b.ToTable("openngc_catalog");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Phd2Calibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("AltDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("alt_deg");

                    b.Property<double?>("AzDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("az_deg");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<double?>("DecDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("dec_deg");

                    b.Property<double?>("DecGuideSpeed")
                        .HasColumnType("REAL")
                        .HasColumnName("dec_guide_speed");

                    b.Property<string>("EquipmentProfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("equipment_profile");

                    b.Property<double?>("FocalLengthMm")
                        .HasColumnType("REAL")
                        .HasColumnName("focal_length_mm");

                    b.Property<string>("GuideCamera")
                        .HasColumnType("TEXT")
                        .HasColumnName("guide_camera");

                    b.Property<double?>("HourAngleHr")
                        .HasColumnType("REAL")
                        .HasColumnName("hour_angle_hr");

                    b.Property<Guid>("LogId")
                        .HasColumnType("TEXT")
                        .HasColumnName("log_id");

                    b.Property<string>("MountName")
                        .HasColumnType("TEXT")
                        .HasColumnName("mount_name");

                    b.Property<double?>("NorthAngleDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("north_angle_deg");

                    b.Property<string>("NorthParity")
                        .HasColumnType("TEXT")
                        .HasColumnName("north_parity");

                    b.Property<double?>("NorthRatePxS")
                        .HasColumnType("REAL")
                        .HasColumnName("north_rate_px_s");

                    b.Property<string>("PierSide")
                        .HasColumnType("TEXT")
                        .HasColumnName("pier_side");

                    b.Property<double?>("PixelScaleArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("pixel_scale_arcsec");

                    b.Property<double?>("RaGuideSpeed")
                        .HasColumnType("REAL")
                        .HasColumnName("ra_guide_speed");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<DateTime>("StartedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_local");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("steps");

                    b.Property<string>("Telescope")
                        .HasColumnType("TEXT")
                        .HasColumnName("telescope");

                    b.Property<double?>("WestAngleDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("west_angle_deg");

                    b.Property<string>("WestParity")
                        .HasColumnType("TEXT")
                        .HasColumnName("west_parity");

                    b.Property<double?>("WestRatePxS")
                        .HasColumnType("REAL")
                        .HasColumnName("west_rate_px_s");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .HasDatabaseName("ix_phd2_calibrations_log_id");

                    b.HasIndex("SessionDate")
                        .HasDatabaseName("ix_phd2_calibrations_session_date");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_phd2_calibrations_started_at_utc");

                    b.ToTable("phd2_calibrations");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Phd2Frame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DecDirection")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dec_direction");

                    b.Property<int>("DecDurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dec_duration_ms");

                    b.Property<double?>("DecGuide")
                        .HasColumnType("REAL")
                        .HasColumnName("dec_guide");

                    b.Property<double?>("DecRaw")
                        .HasColumnType("REAL")
                        .HasColumnName("dec_raw");

                    b.Property<bool>("Dropped")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropped");

                    b.Property<double?>("Dx")
                        .HasColumnType("REAL")
                        .HasColumnName("dx");

                    b.Property<double?>("Dy")
                        .HasColumnType("REAL")
                        .HasColumnName("dy");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("error_code");

                    b.Property<int>("FrameIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frame_index");

                    b.Property<string>("RaDirection")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ra_direction");

                    b.Property<int>("RaDurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ra_duration_ms");

                    b.Property<double?>("RaGuide")
                        .HasColumnType("REAL")
                        .HasColumnName("ra_guide");

                    b.Property<double?>("RaRaw")
                        .HasColumnType("REAL")
                        .HasColumnName("ra_raw");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<double?>("Snr")
                        .HasColumnType("REAL")
                        .HasColumnName("snr");

                    b.Property<double?>("StarMass")
                        .HasColumnType("REAL")
                        .HasColumnName("star_mass");

                    b.Property<double>("TimeOffset")
                        .HasColumnType("REAL")
                        .HasColumnName("time_offset");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "FrameIndex")
                        .HasDatabaseName("ix_phd2_frames_session_frame");

                    b.HasIndex("SessionId", "TimeOffset")
                        .HasDatabaseName("ix_phd2_frames_session_time");

                    b.ToTable("phd2_frames");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Phd2Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CalibrationCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("calibration_count");

                    b.Property<double?>("FileMtime")
                        .HasColumnType("REAL")
                        .HasColumnName("file_mtime");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path")
                        .UseCollation("NOCASE");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("LogVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("log_version");

                    b.Property<string>("ParseError")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_error");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_status");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("parsed_at");

                    b.Property<string>("Phd2Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("phd2_version");

                    b.Property<int>("RunCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_count");

                    b.Property<int>("SessionCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_count");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("ix_phd2_logs_file_path");

                    b.ToTable("phd2_logs");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Phd2Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("AggressionRa")
                        .HasColumnType("REAL")
                        .HasColumnName("aggression_ra");

                    b.Property<string>("AlgoDec")
                        .HasColumnType("TEXT")
                        .HasColumnName("algo_dec");

                    b.Property<string>("AlgoRa")
                        .HasColumnType("TEXT")
                        .HasColumnName("algo_ra");

                    b.Property<double?>("AltDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("alt_deg");

                    b.Property<double?>("AzDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("az_deg");

                    b.Property<double?>("DecDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("dec_deg");

                    b.Property<string>("DecGuideMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("dec_guide_mode");

                    b.Property<int>("DiscardedRows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discarded_rows");

                    b.Property<int>("DitherCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dither_count");

                    b.Property<int>("DropCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drop_count");

                    b.Property<double>("DurationS")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_s");

                    b.Property<DateTime?>("EndedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at_local");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("EquipmentProfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("equipment_profile");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("events");

                    b.Property<double?>("ExposureMs")
                        .HasColumnType("REAL")
                        .HasColumnName("exposure_ms");

                    b.Property<double?>("FocalLengthMm")
                        .HasColumnType("REAL")
                        .HasColumnName("focal_length_mm");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frame_count");

                    b.Property<string>("GuideCamera")
                        .HasColumnType("TEXT")
                        .HasColumnName("guide_camera");

                    b.Property<double?>("HourAngleHr")
                        .HasColumnType("REAL")
                        .HasColumnName("hour_angle_hr");

                    b.Property<string>("LastCalIssue")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_cal_issue");

                    b.Property<Guid>("LogId")
                        .HasColumnType("TEXT")
                        .HasColumnName("log_id");

                    b.Property<int>("MaxDropRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_drop_run");

                    b.Property<double?>("MinMoveDec")
                        .HasColumnType("REAL")
                        .HasColumnName("min_move_dec");

                    b.Property<double?>("MinMoveRa")
                        .HasColumnType("REAL")
                        .HasColumnName("min_move_ra");

                    b.Property<string>("MountName")
                        .HasColumnType("TEXT")
                        .HasColumnName("mount_name");

                    b.Property<double?>("OrthoErrorDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("ortho_error_deg");

                    b.Property<double?>("PeakDecArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("peak_dec_arcsec");

                    b.Property<double?>("PeakRaArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("peak_ra_arcsec");

                    b.Property<string>("PierSide")
                        .HasColumnType("TEXT")
                        .HasColumnName("pier_side");

                    b.Property<double?>("PixelScaleArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("pixel_scale_arcsec");

                    b.Property<int>("PulseCountDecNorth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pulse_count_dec_north");

                    b.Property<int>("PulseCountDecSouth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pulse_count_dec_south");

                    b.Property<int>("PulseCountRaEast")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pulse_count_ra_east");

                    b.Property<int>("PulseCountRaWest")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pulse_count_ra_west");

                    b.Property<long>("PulseTotalMsDec")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pulse_total_ms_dec");

                    b.Property<long>("PulseTotalMsRa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pulse_total_ms_ra");

                    b.Property<double?>("RmsDecArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("rms_dec_arcsec");

                    b.Property<double?>("RmsDecFilteredArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("rms_dec_filtered_arcsec");

                    b.Property<double?>("RmsRaArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("rms_ra_arcsec");

                    b.Property<double?>("RmsRaFilteredArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("rms_ra_filtered_arcsec");

                    b.Property<double?>("RmsTotalArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("rms_total_arcsec");

                    b.Property<double?>("RmsTotalFilteredArcsec")
                        .HasColumnType("REAL")
                        .HasColumnName("rms_total_filtered_arcsec");

                    b.Property<int>("RunIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_index");

                    b.Property<int>("SectionIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("section_index");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<int>("SettleCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("settle_count");

                    b.Property<int>("SettleFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("settle_failed_count");

                    b.Property<double?>("SettleMedianS")
                        .HasColumnType("REAL")
                        .HasColumnName("settle_median_s");

                    b.Property<double?>("SnrMean")
                        .HasColumnType("REAL")
                        .HasColumnName("snr_mean");

                    b.Property<double?>("SnrMin")
                        .HasColumnType("REAL")
                        .HasColumnName("snr_min");

                    b.Property<string>("StarLostReasons")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("star_lost_reasons");

                    b.Property<double?>("StarMassMean")
                        .HasColumnType("REAL")
                        .HasColumnName("star_mass_mean");

                    b.Property<DateTime>("StartedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_local");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Telescope")
                        .HasColumnType("TEXT")
                        .HasColumnName("telescope");

                    b.Property<bool>("Truncated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("truncated");

                    b.Property<double>("UnguidedSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("unguided_seconds");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .HasDatabaseName("ix_phd2_sessions_log_id");

                    b.HasIndex("SessionDate")
                        .HasDatabaseName("ix_phd2_sessions_session_date");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_phd2_sessions_started_at_utc");

                    b.HasIndex("Telescope", "SessionDate")
                        .HasDatabaseName("ix_phd2_sessions_telescope_session_date");

                    b.ToTable("phd2_sessions");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.ScanRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChangedFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("changed_files");

                    b.Property<int>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<int>("Discovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discovered");

                    b.Property<string>("ErrorText")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_text");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<int>("NewFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_files");

                    b.Property<int>("Phd2Failed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("phd2_failed");

                    b.Property<int>("Phd2Found")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("phd2_found");

                    b.Property<int>("Phd2Ingested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("phd2_ingested");

                    b.Property<int>("Removed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("removed");

                    b.Property<int>("SkippedCalibration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skipped_calibration");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending();

                    b.ToTable("scan_runs");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.SessionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TargetId", "SessionDate")
                        .IsUnique();

                    b.ToTable("session_notes");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.StaticCatalogEntry", b =>
                {
                    b.Property<string>("CatalogName")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_name");

                    b.Property<string>("CatalogNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_number");

                    b.Property<string>("NgcName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ngc_name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.HasKey("CatalogName", "CatalogNumber");

                    b.HasIndex("CatalogName", "NgcName");

                    b.ToTable("static_catalog_entries");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aliases");

                    b.Property<string>("CatalogId")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_id");

                    b.Property<string>("CatalogIdNormalized")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_id_normalized");

                    b.Property<string>("CommonName")
                        .HasColumnType("TEXT")
                        .HasColumnName("common_name");

                    b.Property<string>("Constellation")
                        .HasColumnType("TEXT")
                        .HasColumnName("constellation");

                    b.Property<double?>("Dec")
                        .HasColumnType("REAL")
                        .HasColumnName("dec");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("merged_at");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("merged_into_id");

                    b.Property<bool>("NameLocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name_locked");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ObjectType")
                        .HasColumnType("TEXT")
                        .HasColumnName("object_type");

                    b.Property<double?>("PositionAngle")
                        .HasColumnType("REAL")
                        .HasColumnName("position_angle");

                    b.Property<string>("PrimaryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_name");

                    b.Property<double?>("Ra")
                        .HasColumnType("REAL")
                        .HasColumnName("ra");

                    b.Property<string>("ReferenceThumbnailPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_thumbnail_path");

                    b.Property<string>("SacDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("sac_description");

                    b.Property<string>("SacNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("sac_notes");

                    b.Property<double?>("SizeMajor")
                        .HasColumnType("REAL")
                        .HasColumnName("size_major");

                    b.Property<double?>("SizeMinor")
                        .HasColumnType("REAL")
                        .HasColumnName("size_minor");

                    b.Property<double?>("SurfaceBrightness")
                        .HasColumnType("REAL")
                        .HasColumnName("surface_brightness");

                    b.Property<bool>("UserDefined")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_defined");

                    b.Property<double?>("VMag")
                        .HasColumnType("REAL")
                        .HasColumnName("v_mag");

                    b.HasKey("Id");

                    b.HasIndex("CatalogIdNormalized")
                        .IsUnique()
                        .HasFilter("catalog_id_normalized IS NOT NULL AND merged_into_id IS NULL");

                    b.HasIndex("MergedIntoId");

                    b.HasIndex("PrimaryName")
                        .IsUnique()
                        .HasFilter("merged_into_id IS NULL");

                    b.ToTable("targets");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.TargetCatalogMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CatalogName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_name");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_number");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("TargetId", "CatalogName")
                        .IsUnique();

                    b.ToTable("target_catalog_memberships");
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.UserSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DismissedSuggestions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dismissed_suggestions");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("equipment");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filters");

                    b.Property<string>("General")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("general");

                    b.Property<string>("Graph")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("graph");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("user_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_settings_id", "id = 1");
                        });
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.ActivityEvent", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.ActivityEvent", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.CustomColumnValue", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.CustomColumn", null)
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Image", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("ResolvedTargetId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.MergeCandidate", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("SuggestedTargetId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.MergeManifest", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("LoserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Phd2Calibration", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Phd2Log", null)
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Phd2Frame", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Phd2Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Phd2Session", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Phd2Log", null)
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.SessionNote", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.Target", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GalactiLog.Data.Entities.TargetCatalogMembership", b =>
                {
                    b.HasOne("GalactiLog.Data.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
